services:
  - type: web
    name: emis-exam-portal
    runtime: python
    plan: starter
    region: frankfurt
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: pythonVersion
        value: "3.11"
