services:
  web:
    type: web
    name: emis-exam-portal
    runtime: python
    plan: starter
    region: frankfurt
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      pythonVersion: 3.11
